# environment.yml
name: nnpdf
channels:
  - pytorch
  - conda-forge
dependencies:
  - python=3.11
  - pip

  # core stack
  - nnpdf=4.0.10
  - numpy
  - scipy
  - pandas
  - scikit-learn
  - matplotlib
  - seaborn
  - pyarrow
  - numba
  - llvmlite=0.42.0

  # ML frameworks
  - pytorch
  - torchvision
  - torchaudio
  - tensorflow=2.18   # or pin exactly if you want

